#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

. "${PWD}/.dev/utility.sh"

install_git_hooks() {
    if [[ -d "${ROOT_DIR}/.git" ]]; then
        rm -rf "${ROOT_DIR}/.git/hooks"
        ln -s ../.dev/git-hooks "${ROOT_DIR}/.git/hooks"
        chmod +x "${ROOT_DIR}/.dev/git-hooks"/* 2>/dev/null || true
    fi
}

install_git_hooks

docker_compose "$@"
