package migration

import (
    "context"

    "github.com/uptrace/bun"
)

func init() {
    JournalMigrations.MustRegister(upJournalSchema, downJournalSchema)
}

/* upJournalSchema creates the journal table. It is a set of its own because the journal is a database of its own — postgres, beside the mysql catalog — and bookkeeping is per database; the same single-state rule applies to it as to its sibling. */
func upJournalSchema(ctx context.Context, database *bun.DB) error {
    _, execErr := database.ExecContext(ctx, createCatalogJournalTableSql)

    return execErr
}

/* journalTableName is unquoted where its catalog siblings are backticked, because this one statement is
   postgres dialect: the journal is a database of its own. */
const journalTableName = "melody_example_v1_catalog_journal"

func downJournalSchema(ctx context.Context, database *bun.DB) error {
    _, execErr := database.ExecContext(ctx, "DROP TABLE IF EXISTS "+journalTableName)

    return execErr
}

/* the journal is the one table with a database-assigned identifier: entries are append-only and never constructed with an id of their own. The statement is postgres dialect — identity instead of AUTO_INCREMENT, timestamptz instead of datetime — because the journal set applies to the journal database alone. */
const createCatalogJournalTableSql = "CREATE TABLE IF NOT EXISTS melody_example_v1_catalog_journal (" +
    "id BIGINT GENERATED BY DEFAULT AS IDENTITY, " +
    "actor VARCHAR(255) NOT NULL, " +
    "action VARCHAR(255) NOT NULL, " +
    "subject VARCHAR(255) NOT NULL, " +
    "subject_id VARCHAR(255) NOT NULL, " +
    "recorded_at TIMESTAMPTZ(6) NOT NULL, " +
    "PRIMARY KEY (id))"
