package migration

import (
    "context"
    "strings"
    "testing"
)

/* the two sets are ONE migration each because the example has one state, so what is pinned here is the
   CONTENT of each migration — which statements it emits, and in what order — rather than how many steps
   the schema is spread over. The counts this replaced could not see either: a set of four steps emitted
   backwards would have satisfied them. */
func TestMigrationsHoldOneSchemaMigrationPerDatabase(t *testing.T) {
    sorted := Migrations.Sorted()
    if 1 != len(sorted) {
        t.Fatalf("expected the catalog set to hold one migration, got %d", len(sorted))
    }
    if "20260907000001" != sorted[0].Name {
        t.Fatalf("expected the catalog migration to be 20260907000001, got %s", sorted[0].Name)
    }
    if nil == sorted[0].Up || nil == sorted[0].Down {
        t.Fatalf("expected migration %s to carry both directions", sorted[0].Name)
    }

    journalSorted := JournalMigrations.Sorted()
    if 1 != len(journalSorted) {
        t.Fatalf("expected the journal set to hold one migration, got %d", len(journalSorted))
    }
    if "20260907000002" != journalSorted[0].Name {
        t.Fatalf("expected the journal migration to be 20260907000002, got %s", journalSorted[0].Name)
    }
    if nil == journalSorted[0].Up || nil == journalSorted[0].Down {
        t.Fatalf("expected migration %s to carry both directions", journalSorted[0].Name)
    }
}

func TestUpSchemaCreatesEveryCatalogTableTolerantly(t *testing.T) {
    database, recorder := newFakeBunDatabase()

    if upErr := upSchema(context.Background(), database); nil != upErr {
        t.Fatalf("expected the up migration to succeed, got %v", upErr)
    }

    assertQueryOrder(t, recorder.recordedQueries(), []string{
        "CREATE TABLE IF NOT EXISTS `melody_example_v1_category`",
        "CREATE TABLE IF NOT EXISTS `melody_example_v1_currency`",
        "CREATE TABLE IF NOT EXISTS `melody_example_v1_product`",
        "CREATE TABLE IF NOT EXISTS `melody_example_v1_user`",
    })
}

func TestDownSchemaDropsTheCatalogTablesInReverse(t *testing.T) {
    database, recorder := newFakeBunDatabase()

    if downErr := downSchema(context.Background(), database); nil != downErr {
        t.Fatalf("expected the down migration to succeed, got %v", downErr)
    }

    assertQueryOrder(t, recorder.recordedQueries(), []string{
        "DROP TABLE IF EXISTS `melody_example_v1_user`",
        "DROP TABLE IF EXISTS `melody_example_v1_product`",
        "DROP TABLE IF EXISTS `melody_example_v1_currency`",
        "DROP TABLE IF EXISTS `melody_example_v1_category`",
    })
}

/* the journal statement is postgres dialect while its sibling is mysql, which is the reason the two live
   in sets of their own: bookkeeping is per database, and so is the spelling. */
func TestUpJournalSchemaCreatesTheJournalTableInThePostgresSpelling(t *testing.T) {
    database, recorder := newFakeBunDatabase()

    if upErr := upJournalSchema(context.Background(), database); nil != upErr {
        t.Fatalf("expected the up migration to succeed, got %v", upErr)
    }

    assertQueryOrder(t, recorder.recordedQueries(), []string{
        "CREATE TABLE IF NOT EXISTS melody_example_v1_catalog_journal",
    })

    statement := recorder.recordedQueries()[0]

    for _, wanted := range []string{"GENERATED BY DEFAULT AS IDENTITY", "TIMESTAMPTZ(6)"} {
        if false == strings.Contains(statement, wanted) {
            t.Fatalf("expected the postgres spelling to carry %s, got %q", wanted, statement)
        }
    }
}

func TestDownJournalSchemaDropsTheJournalTableTolerantly(t *testing.T) {
    database, recorder := newFakeBunDatabase()

    if downErr := downJournalSchema(context.Background(), database); nil != downErr {
        t.Fatalf("expected the down migration to succeed, got %v", downErr)
    }

    assertQueryOrder(t, recorder.recordedQueries(), []string{
        "DROP TABLE IF EXISTS melody_example_v1_catalog_journal",
    })
}
