package migration

import (
    "context"
    "database/sql/driver"
    "strings"
    "testing"
)

/* the two sets are ONE migration each because the example has one state, so what is pinned here is the CONTENT of each migration, which statements it emits and in what order, rather than how many steps the schema is spread over; a count could not see a set emitted backwards. */
func TestMigrationsHoldOneSchemaMigrationPerDatabase(t *testing.T) {
    sorted := Migrations.Sorted()
    if 1 != len(sorted) {
        t.Fatalf("expected the catalog set to hold one migration, got %d", len(sorted))
    }
    if "20260907000001" != sorted[0].Name {
        t.Fatalf("expected the catalog migration to be 20260907000001, got %s", sorted[0].Name)
    }
    if nil == sorted[0].Up || nil == sorted[0].Down {
        t.Fatalf("expected migration %s to carry both directions", sorted[0].Name)
    }

    journalSorted := JournalMigrations.Sorted()
    if 1 != len(journalSorted) {
        t.Fatalf("expected the journal set to hold one migration, got %d", len(journalSorted))
    }
    if "20260907000002" != journalSorted[0].Name {
        t.Fatalf("expected the journal migration to be 20260907000002, got %s", journalSorted[0].Name)
    }
    if nil == journalSorted[0].Up || nil == journalSorted[0].Down {
        t.Fatalf("expected migration %s to carry both directions", journalSorted[0].Name)
    }
}

func TestUpSchemaCreatesEveryCatalogTableTolerantly(t *testing.T) {
    database, recorder := newFakeBunDatabase()

    if upErr := upSchema(context.Background(), database); nil != upErr {
        t.Fatalf("expected the up migration to succeed, got %v", upErr)
    }

    assertQueryOrder(t, recorder.recordedQueries(), []string{
        "CREATE TABLE IF NOT EXISTS `melody_example_v1_category`",
        "CREATE TABLE IF NOT EXISTS `melody_example_v1_currency`",
        "CREATE TABLE IF NOT EXISTS `melody_example_v1_product`",
        "CREATE TABLE IF NOT EXISTS `melody_example_v1_user`",
        "CREATE TABLE IF NOT EXISTS `melody_example_v1_user_session`",
        "information_schema.STATISTICS",
        "ADD UNIQUE KEY `melody_example_v1_user_username_folded`",
    })
}

func TestDownSchemaDropsTheCatalogTablesInReverse(t *testing.T) {
    database, recorder := newFakeBunDatabase()

    if downErr := downSchema(context.Background(), database); nil != downErr {
        t.Fatalf("expected the down migration to succeed, got %v", downErr)
    }

    assertQueryOrder(t, recorder.recordedQueries(), []string{
        "DROP TABLE IF EXISTS `melody_example_v1_user_session`",
        "DROP TABLE IF EXISTS `melody_example_v1_user`",
        "DROP TABLE IF EXISTS `melody_example_v1_product`",
        "DROP TABLE IF EXISTS `melody_example_v1_currency`",
        "DROP TABLE IF EXISTS `melody_example_v1_category`",
    })
}

/* the journal statement is postgres dialect while its sibling is mysql, which is the reason the two live
   in sets of their own: bookkeeping is per database, and so is the spelling. */
func TestUpJournalSchemaCreatesTheJournalTableInThePostgresSpelling(t *testing.T) {
    database, recorder := newFakeBunDatabase()

    if upErr := upJournalSchema(context.Background(), database); nil != upErr {
        t.Fatalf("expected the up migration to succeed, got %v", upErr)
    }

    assertQueryOrder(t, recorder.recordedQueries(), []string{
        "CREATE TABLE IF NOT EXISTS melody_example_v1_catalog_journal",
    })

    statement := recorder.recordedQueries()[0]

    for _, wanted := range []string{"GENERATED BY DEFAULT AS IDENTITY", "TIMESTAMPTZ(6)"} {
        if false == strings.Contains(statement, wanted) {
            t.Fatalf("expected the postgres spelling to carry %s, got %q", wanted, statement)
        }
    }
}

func TestDownJournalSchemaDropsTheJournalTableTolerantly(t *testing.T) {
    database, recorder := newFakeBunDatabase()

    if downErr := downJournalSchema(context.Background(), database); nil != downErr {
        t.Fatalf("expected the down migration to succeed, got %v", downErr)
    }

    assertQueryOrder(t, recorder.recordedQueries(), []string{
        "DROP TABLE IF EXISTS melody_example_v1_catalog_journal",
    })
}

/* every column that holds an entity identifier is compared under utf8mb4_bin: the identity of an id is exact everywhere else, in the in-memory repositories and the cache keys, and under the table's default collation a lookup by id would fold case and accents, so an alias spelling would find the row and be cached under a key nothing invalidates */
func TestUpSchemaComparesEveryIdentifierColumnByteForByte(t *testing.T) {
    database, recorder := newFakeBunDatabase()

    if upErr := upSchema(context.Background(), database); nil != upErr {
        t.Fatalf("expected the up migration to succeed, got %v", upErr)
    }

    rendered := strings.Join(recorder.recordedQueries(), "\n")

    identifierColumnList := []string{"`id`", "`category_id`", "`currency_id`", "`user_identifier`"}
    collated := 0
    for _, column := range identifierColumnList {
        collated += strings.Count(rendered, column+" VARCHAR(255) COLLATE utf8mb4_bin NOT NULL")

        if uncollated := strings.Count(rendered, column+" VARCHAR(255) NOT NULL"); 0 != uncollated {
            t.Errorf("%s is declared %d time(s) under the table's default collation", column, uncollated)
        }
    }

    if 7 != collated {
        t.Errorf("%d identifier columns are compared under utf8mb4_bin, wanted 7", collated)
    }
}

func TestUpSchemaDoesNotAddTheUsernameIndexASecondTime(t *testing.T) {
    database, recorder := newFakeBunDatabase()
    recorder.queryHook = func(query string) ([]string, [][]driver.Value, error) {
        if true == strings.Contains(query, "information_schema.STATISTICS") {
            return []string{"count"}, [][]driver.Value{{int64(1)}}, nil
        }

        return nil, nil, nil
    }

    if upErr := upSchema(context.Background(), database); nil != upErr {
        t.Fatalf("expected the up migration to succeed over a volume holding the index, got %v", upErr)
    }

    for _, query := range recorder.recordedQueries() {
        if true == strings.Contains(query, "ADD UNIQUE KEY") {
            t.Fatalf("expected the present index not to be added again, got %q", query)
        }
    }
}

/* a session row goes with its account: the key cascades the account's delete, and the session id is compared byte for byte as every identifier is */
func TestUpSchemaCreatesTheSessionIndexUnderTheAccountsKey(t *testing.T) {
    database, recorder := newFakeBunDatabase()

    if upErr := upSchema(context.Background(), database); nil != upErr {
        t.Fatalf("expected the up migration to succeed, got %v", upErr)
    }

    rendered := strings.Join(recorder.recordedQueries(), "\n")
    for _, fragment := range []string{
        "`session_id` VARCHAR(255) COLLATE utf8mb4_bin NOT NULL",
        "KEY `melody_example_v1_user_session_account` (`user_identifier`, `created_at`)",
        "FOREIGN KEY (`user_identifier`) REFERENCES `melody_example_v1_user` (`id`) ON DELETE CASCADE",
    } {
        if false == strings.Contains(rendered, fragment) {
            t.Fatalf("expected the session index to carry %q, got %q", fragment, rendered)
        }
    }
}
