package migration

import (
    "context"

    "github.com/uptrace/bun"
)

func init() {
    Migrations.MustRegister(upCreateCatalogJournal, downCreateCatalogJournal)
}

func upCreateCatalogJournal(ctx context.Context, database *bun.DB) error {
    _, execErr := database.ExecContext(ctx, createCatalogJournalTableSql)

    return execErr
}

func downCreateCatalogJournal(ctx context.Context, database *bun.DB) error {
    _, execErr := database.ExecContext(ctx, "DROP TABLE IF EXISTS `melody_example_v3_catalog_journal`")

    return execErr
}

/* the journal lives on mysql beside the catalogue on this major, so the identity column is written in the mysql spelling; v1 keeps the same table on postgres and spells it GENERATED BY DEFAULT AS IDENTITY. The request identifier is this major's own column: an entry names the call that caused it, and it is empty for a change made outside a request. */
const createCatalogJournalTableSql = "CREATE TABLE IF NOT EXISTS `melody_example_v3_catalog_journal` (" +
    "`id` BIGINT NOT NULL AUTO_INCREMENT, " +
    "`request_id` VARCHAR(255) NOT NULL, " +
    "`actor` VARCHAR(255) NOT NULL, " +
    "`action` VARCHAR(255) NOT NULL, " +
    "`subject` VARCHAR(255) NOT NULL, " +
    "`subject_id` VARCHAR(255) NOT NULL, " +
    "`recorded_at` DATETIME(6) NOT NULL, " +
    "PRIMARY KEY (`id`))"
