package migration

import (
    "context"

    "github.com/uptrace/bun"
)

func init() {
    Migrations.MustRegister(upSchema, downSchema)
}

/* UserUsernameIndexName is the one spelling of the index. The schema owns it, so this step and the repository that maps the driver's duplicate-key refusal onto the public message read the same constant: a name written in two places is a constraint and a refusal that can drift apart. */
const UserUsernameIndexName = "melody_example_v3_user_username_folded"

/* upSchema creates the six tables this example owns and declares the one constraint it needs, in one step. The set is one migration rather than a history of them because this application has no history: an example has a single state, the present one, and its schema is the statement of that state. A volume left in an older shape is brought to it by example:db:reset, not by a step that repairs its past.

   Every statement tolerates a volume provisioned before the set, and several processes of this example applying it at the same time: the tables are created IF NOT EXISTS, and the constraint — MySQL having no ADD KEY IF NOT EXISTS — is added only after the catalogue is asked whether it is already there.

   The constraint comes last because it is declared on a table this step has just created. */
func upSchema(ctx context.Context, database *bun.DB) error {
    for _, statement := range schemaUpStatementList {
        if _, execErr := database.ExecContext(ctx, statement); nil != execErr {
            return execErr
        }
    }

    return addUserUsernameIndex(ctx, database)
}

/* downSchema reverses upSchema: the constraint goes first, because the table it stands on is one of the ones the drops below take away, and the tables go in the reverse order of their creation. */
func downSchema(ctx context.Context, database *bun.DB) error {
    if dropIndexErr := dropUserUsernameIndex(ctx, database); nil != dropIndexErr {
        return dropIndexErr
    }

    for _, statement := range schemaDownStatementList {
        if _, execErr := database.ExecContext(ctx, statement); nil != execErr {
            return execErr
        }
    }

    return nil
}

/* the column definitions mirror the tables the bun create-table builder used to produce, captured from a live SHOW CREATE TABLE, so a volume provisioned before the migration set and one provisioned by it hold the same schema */
const createCategoryTableSql = "CREATE TABLE IF NOT EXISTS `melody_example_v3_category` (" +
    "`id` VARCHAR(255) NOT NULL, " +
    "`name` VARCHAR(255) NOT NULL, " +
    "PRIMARY KEY (`id`))"

const createCurrencyTableSql = "CREATE TABLE IF NOT EXISTS `melody_example_v3_currency` (" +
    "`id` VARCHAR(255) NOT NULL, " +
    "`code` VARCHAR(255) NOT NULL, " +
    "`name` VARCHAR(255) NOT NULL, " +
    "PRIMARY KEY (`id`))"

/* the two instants are DATETIME(6) because the model declares them so: a product created and updated inside the same second is ordered by the microseconds, and a DATETIME without them would collapse the pair */
const createProductTableSql = "CREATE TABLE IF NOT EXISTS `melody_example_v3_product` (" +
    "`id` VARCHAR(255) NOT NULL, " +
    "`name` VARCHAR(255) NOT NULL, " +
    "`description` VARCHAR(255) NOT NULL, " +
    "`category_id` VARCHAR(255) NOT NULL, " +
    "`price` DOUBLE NOT NULL, " +
    "`currency_id` VARCHAR(255) NOT NULL, " +
    "`stock` BIGINT NOT NULL, " +
    "`created_at` DATETIME(6) NOT NULL, " +
    "`updated_at` DATETIME(6) NOT NULL, " +
    "PRIMARY KEY (`id`))"

/* the password column holds a bcrypt digest, never a password; the audit registry is told so by the model's own redact tag, and the width is the one the model produced */
const createUserTableSql = "CREATE TABLE IF NOT EXISTS `melody_example_v3_user` (" +
    "`id` VARCHAR(255) NOT NULL, " +
    "`username` VARCHAR(255) NOT NULL, " +
    "`password` VARCHAR(255) NOT NULL, " +
    "`roles` VARCHAR(255) NOT NULL, " +
    "PRIMARY KEY (`id`))"

/* the journal lives on mysql beside the catalogue on this major, so the identity column is written in the mysql spelling; v1 keeps the same table on postgres and spells it GENERATED BY DEFAULT AS IDENTITY. The request identifier is this major's own column: an entry names the call that caused it, and it is empty for a change made outside a request. */
const createCatalogJournalTableSql = "CREATE TABLE IF NOT EXISTS `melody_example_v3_catalog_journal` (" +
    "`id` BIGINT NOT NULL AUTO_INCREMENT, " +
    "`request_id` VARCHAR(255) NOT NULL, " +
    "`actor` VARCHAR(255) NOT NULL, " +
    "`action` VARCHAR(255) NOT NULL, " +
    "`subject` VARCHAR(255) NOT NULL, " +
    "`subject_id` VARCHAR(255) NOT NULL, " +
    "`recorded_at` DATETIME(6) NOT NULL, " +
    "PRIMARY KEY (`id`))"

/* the two secret columns are VARBINARY because bunorm's EncryptedString writes a sealed byte string, not text: a character set would try to interpret ciphertext and a collation would compare it. The widths are the ones the model declares, and they hold the sealed spelling rather than the plaintext — the marker, key identifier, nonce and tag travel with it. This table is the one neither frozen major carries. */
const createTwoFactorTableSql = "CREATE TABLE IF NOT EXISTS `melody_example_v3_two_factor` (" +
    "`user_identifier` VARCHAR(255) NOT NULL, " +
    "`secret` VARBINARY(512) NOT NULL, " +
    "`recovery_codes` VARBINARY(2048) NOT NULL, " +
    "`created_at` DATETIME NOT NULL, " +
    "PRIMARY KEY (`user_identifier`))"

/* the index is on LOWER(username) cast to the binary collation because that expression, and only that
   expression, is the identity this application gives a username: NormalizedUsername folds case and
   nothing else, and the lookup door compares on utf8mb4_bin for the same reason. Indexed on the column
   as it stands, the constraint would follow the column's own utf8mb4_0900_ai_ci and refuse two names the
   application considers different — 'ana' and 'ána' — while admitting 'Ana' beside 'ana', which it
   considers the same. Measured on the running server: with this expression 'ana' and 'ANA' collide with
   'Ana', 'Ána' does not, which is exactly what the lookup answers. */
const createUserUsernameIndexSql = "ALTER TABLE `melody_example_v3_user` " +
    "ADD UNIQUE KEY `" + UserUsernameIndexName + "` " +
    "((CAST(LOWER(`username`) AS CHAR(255) CHARACTER SET utf8mb4) COLLATE utf8mb4_bin))"

var schemaUpStatementList = []string{
    createCategoryTableSql,
    createCurrencyTableSql,
    createProductTableSql,
    createUserTableSql,
    createCatalogJournalTableSql,
    createTwoFactorTableSql,
}

/* schemaTableNameList names the tables this migration owns, in the order it drops them — the reverse of
   the order it creates them in. The drop statements are DERIVED from it, so a table added to the schema
   cannot be left standing by a down that forgot it, and the reset command names the same list to the
   operator rather than a second copy of it. */
var schemaTableNameList = []string{
    "melody_example_v3_two_factor",
    "melody_example_v3_catalog_journal",
    "melody_example_v3_user",
    "melody_example_v3_product",
    "melody_example_v3_currency",
    "melody_example_v3_category",
}

var schemaDownStatementList = dropStatementList(schemaTableNameList)

func dropStatementList(tableNameList []string) []string {
    statementList := make([]string, 0, len(tableNameList))
    for _, table := range tableNameList {
        statementList = append(statementList, "DROP TABLE IF EXISTS `"+table+"`")
    }

    return statementList
}

/* the set's own discipline is that a step tolerates a volume provisioned before it — every table is
   created IF NOT EXISTS. MySQL has no ADD KEY IF NOT EXISTS, so the same tolerance is spelled by asking
   the catalogue first; without it a volume whose table was created by a build that already carries the
   key would fail the step on a duplicate index name. */
func addUserUsernameIndex(ctx context.Context, database *bun.DB) error {
    present, presentErr := userUsernameIndexIsPresent(ctx, database)
    if nil != presentErr {
        return presentErr
    }

    if true == present {
        return nil
    }

    _, execErr := database.ExecContext(ctx, createUserUsernameIndexSql)

    return execErr
}

func dropUserUsernameIndex(ctx context.Context, database *bun.DB) error {
    present, presentErr := userUsernameIndexIsPresent(ctx, database)
    if nil != presentErr {
        return presentErr
    }

    if false == present {
        return nil
    }

    _, execErr := database.ExecContext(
        ctx,
        "ALTER TABLE `melody_example_v3_user` DROP INDEX `"+UserUsernameIndexName+"`",
    )

    return execErr
}

func userUsernameIndexIsPresent(ctx context.Context, database *bun.DB) (bool, error) {
    count := 0

    queryErr := database.NewRaw(
        "SELECT COUNT(*) FROM information_schema.STATISTICS "+
            "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = ? AND INDEX_NAME = ?",
        "melody_example_v3_user",
        UserUsernameIndexName,
    ).Scan(ctx, &count)
    if nil != queryErr {
        return false, queryErr
    }

    return 0 < count, nil
}
