// Code generated by melody:wiring:generate. DO NOT EDIT.

package wiring

import (
    melodyconfig "github.com/precision-soft/melody/v3/config"
    melodycontainer "github.com/precision-soft/melody/v3/container"
    containercontract "github.com/precision-soft/melody/v3/container/contract"
    melodyexception "github.com/precision-soft/melody/v3/exception"
    domain "github.com/precision-soft/melody/v3/wiring/internal/fixture/domain"
    contract "github.com/precision-soft/melody/v3/wiring/internal/fixture/domain/contract"
    math "math"
)

/* RegisterFixtureServices registers every service discovered under the scanned packages. */
func RegisterFixtureServices(registrar containercontract.Registrar) {
    melodycontainer.MustRegisterType(
        registrar,
        func(resolver containercontract.Resolver) (domain.AuditTrail, error) {
            var zeroValue domain.AuditTrail

            repository, repositoryErr := melodycontainer.FromResolverByType[*domain.UserRepository](resolver)
            if nil != repositoryErr {
                return zeroValue, repositoryErr
            }

            return domain.NewAuditTrail(
                repository,
            )
        },
    )

    melodycontainer.MustRegister(
        registrar,
        domain.ServiceCollisionProbe,
        func(resolver containercontract.Resolver) (*domain.CollisionProbe, error) {
            configuration := melodyconfig.ConfigMustFromResolver(resolver)

            domain2, domain2Err := melodycontainer.FromResolverByType[*domain.UserRepository](resolver)
            if nil != domain2Err {
                return nil, domain2Err
            }

            contract2, contract2Err := melodycontainer.FromResolverByType[contract.Logger](resolver)
            if nil != contract2Err {
                return nil, contract2Err
            }

            configuration2, configuration2Err := melodycontainer.FromResolverByType[*domain.UserRepository](resolver)
            if nil != configuration2Err {
                return nil, configuration2Err
            }

            resolver2, resolver2Err := melodycontainer.FromResolverByType[*domain.UserRepository](resolver)
            if nil != resolver2Err {
                return nil, resolver2Err
            }

            retryCount, retryCountErr := configuration.MustGet("fixture.retry_count").Int()
            if nil != retryCountErr {
                return nil, retryCountErr
            }

            refreshBudgetValue, refreshBudgetErr := configuration.MustGet("fixture.refresh_budget").Int()
            if nil != refreshBudgetErr {
                return nil, refreshBudgetErr
            }

            if refreshBudgetValue < 0 || math.MaxUint32 < int64(refreshBudgetValue) {
                return nil, melodyexception.NewError(
                    "a configuration parameter does not fit the constructor argument",
                    map[string]any{
                        "parameter": "fixture.refresh_budget",
                        "argument": "refreshBudget",
                        "argumentType": "uint32",
                    },
                    nil,
                )
            }

            refreshBudget := uint32(refreshBudgetValue)

            return domain.NewCollisionProbe(
                domain2,
                contract2,
                configuration2,
                resolver2,
                retryCount,
                refreshBudget,
            )
        },
    )

    melodycontainer.MustRegisterType(
        registrar,
        func(resolver containercontract.Resolver) (*domain.InvoiceService, error) {
            configuration := melodyconfig.ConfigMustFromResolver(resolver)

            repository, repositoryErr := melodycontainer.FromResolverByType[*domain.UserRepository](resolver)
            if nil != repositoryErr {
                return nil, repositoryErr
            }

            apiUrl := configuration.MustGet("fixture.api_url").MustString()

            retryCount, retryCountErr := configuration.MustGet("fixture.retry_count").Int()
            if nil != retryCountErr {
                return nil, retryCountErr
            }

            return domain.NewInvoiceService(
                repository,
                apiUrl,
                retryCount,
            ), nil
        },
    )

    melodycontainer.MustRegisterType(
        registrar,
        func(resolver containercontract.Resolver) (*domain.ParameterEcho, error) {
            parameter, parameterErr := melodycontainer.FromResolverByType[*melodyconfig.Parameter](resolver)
            if nil != parameterErr {
                return nil, parameterErr
            }

            return domain.NewParameterEcho(
                parameter,
            ), nil
        },
    )

    melodycontainer.MustRegisterType(
        registrar,
        func(resolver containercontract.Resolver) (*domain.ReportingService, error) {
            configuration := melodyconfig.ConfigMustFromResolver(resolver)

            reportingUrl := configuration.MustGet("fixture.reporting_url").MustString()

            return domain.NewReportingService(
                reportingUrl,
            ), nil
        },
    )

    melodycontainer.MustRegisterType(
        registrar,
        func(resolver containercontract.Resolver) (*domain.RetryPolicy, error) {
            configuration := melodyconfig.ConfigMustFromResolver(resolver)

            maxAttemptsValue, maxAttemptsErr := configuration.MustGet("fixture.max_attempts").Int()
            if nil != maxAttemptsErr {
                return nil, maxAttemptsErr
            }

            if maxAttemptsValue < 0 || math.MaxUint8 < maxAttemptsValue {
                return nil, melodyexception.NewError(
                    "a configuration parameter does not fit the constructor argument",
                    map[string]any{
                        "parameter": "fixture.max_attempts",
                        "argument": "maxAttempts",
                        "argumentType": "uint8",
                    },
                    nil,
                )
            }

            maxAttempts := uint8(maxAttemptsValue)

            return domain.NewRetryPolicy(
                maxAttempts,
            ), nil
        },
    )

    melodycontainer.MustRegisterType(
        registrar,
        func(resolver containercontract.Resolver) (*domain.UserRepository, error) {
            return domain.NewUserRepository(), nil
        },
    )

    melodycontainer.MustRegisterType(
        registrar,
        func(resolver containercontract.Resolver) (*domain.UserService, error) {
            configuration := melodyconfig.ConfigMustFromResolver(resolver)

            repository, repositoryErr := melodycontainer.FromResolverByType[*domain.UserRepository](resolver)
            if nil != repositoryErr {
                return nil, repositoryErr
            }

            logger, loggerErr := melodycontainer.FromResolverByType[contract.Logger](resolver)
            if nil != loggerErr {
                return nil, loggerErr
            }

            sessionTtl, sessionTtlErr := configuration.MustGet("fixture.session_ttl").Duration()
            if nil != sessionTtlErr {
                return nil, sessionTtlErr
            }

            stageEnv, stageEnvErr := configuration.MustGet("fixture.stage_env").Bool()
            if nil != stageEnvErr {
                return nil, stageEnvErr
            }

            return domain.NewUserService(
                repository,
                logger,
                sessionTtl,
                stageEnv,
            )
        },
    )
}
