package wiring

import (
    "go/token"
    "sort"
    "strconv"
    "strings"

    "github.com/precision-soft/melody/v3/exception"
)

const (
    indent            = "    "
    generatedFileNote = "// Code generated by melody:wiring:generate. DO NOT EDIT."

    configImportPath             = "github.com/precision-soft/melody/v3/config"
    containerImportPath          = "github.com/precision-soft/melody/v3/container"
    containerContractImportPath  = "github.com/precision-soft/melody/v3/container/contract"
    exceptionImportPath          = "github.com/precision-soft/melody/v3/exception"
    mathImportPath               = "math"
    containerContractImportAlias = "containercontract"
    configImportAlias            = "melodyconfig"
    containerImportAlias         = "melodycontainer"
    exceptionImportAlias         = "melodyexception"
    mathImportAlias              = "math"
)

type GenerateRequest struct {
    ProjectDirectory string
    PackageName      string
    FunctionName     string
    /* ScopedFunctionName names the function the scope-owned registrations are emitted into. It defaults to the container function's name with Scoped appended, and the function is only emitted when something carries the scoped directive. */
    ScopedFunctionName string
    BindSet            *BindSet
    /* DeclaredParameters is the set of parameter names the application declares. When it is empty the generator cannot check a bind target and says so instead of assuming the target exists. */
    DeclaredParameters map[string]bool
    /* BuildTags are the build tags the target binary carries, so a constructor gated on one of them is scanned rather than dropped. */
    BuildTags []string
}

type GenerateReport struct {
    ConstructorCount int
    /* ScopedConstructorCount counts the constructors emitted into the scoped registration function, so the command can report the two lifetimes apart. */
    ScopedConstructorCount int
    Skipped                []*SkippedConstructor
    /* SkippedVendorDirectories names the vendor trees the scan stepped over; strict does not fail on them — they cannot contribute services — but the command can name them on request. */
    SkippedVendorDirectories []string
    /* ExcludedFiles names the build-excluded files that hold a constructor candidate; strict does not fail on them, but the command can name them on request so a missing service traces back to the tag it needs. */
    ExcludedFiles   []string
    UnusedBinds     []string
    GlobalBindReach map[string][]string
    /* UnusedExcludes names the exclude patterns that matched no constructor, each prefixed with its package's import path. An exclusion that stopped matching silently registers the constructor it was declared to keep out, so strict fails on it the way it fails on an unused bind. */
    UnusedExcludes []string
    /* BindTargetsUnchecked reports that a bind resolved while DeclaredParameters was empty, so its target could not be checked against anything. The generator promises to say so rather than silently assume the target exists; the command never trips this — it always hands over the running configuration — but a direct Generate caller can. */
    BindTargetsUnchecked bool
}

/* Generate scans every declared package and renders the registration source. It fails on the first constructor whose scalar argument no bind covers: an unfilled scalar has no safe default, and letting it through would move the failure to a runtime far from its cause. */
func Generate(request *GenerateRequest) (string, *GenerateReport, error) {
    if nil == request || nil == request.BindSet {
        return "", nil, exception.NewError("a bind set is required to generate the wiring", nil, nil)
    }

    functionName := request.FunctionName
    if "" == functionName {
        functionName = "RegisterGeneratedServices"
    }

    scopedFunctionName := request.ScopedFunctionName
    if "" == scopedFunctionName {
        scopedFunctionName = functionName + "Scoped"
    }

    report := &GenerateReport{
        Skipped:                  make([]*SkippedConstructor, 0),
        SkippedVendorDirectories: make([]string, 0),
        ExcludedFiles:            make([]string, 0),
        UnusedBinds:              make([]string, 0),
        GlobalBindReach:          make(map[string][]string),
        UnusedExcludes:           make([]string, 0),
    }

    usedBinds := make(map[string]bool)

    /* every fixed alias is reserved before any scanned type can claim its name: a scanned argument living in one of these packages then renders through the same alias the emitted bodies use, instead of racing them for it */
    importAliases := newImportAliasTable()

    /* both names land verbatim in the generated source, so anything the file cannot carry fails here, at its cause: a non-identifier (keywords included) does not parse — or splices arbitrary tokens into the file — while the blank identifier and init are identifiers the spec still refuses in these positions (an unusable package name, an unreferenceable function, an init that must not have a signature) */
    if false == token.IsIdentifier(functionName) || "_" == functionName || "init" == functionName {
        return "", nil, exception.NewError(
            "the generated function name cannot be declared and referenced in the generated file",
            map[string]any{
                "function": functionName,
            },
            nil,
        )
    }

    if false == token.IsIdentifier(scopedFunctionName) || "_" == scopedFunctionName || "init" == scopedFunctionName {
        return "", nil, exception.NewError(
            "the generated scoped function name cannot be declared and referenced in the generated file",
            map[string]any{
                "function": scopedFunctionName,
            },
            nil,
        )
    }

    /* the two functions share one file, so one name cannot serve both: the second declaration would not compile, and which of the two lifetimes survived would be a coin flip */
    if functionName == scopedFunctionName {
        return "", nil, exception.NewError(
            "the generated function names must differ, or the file declares the same function twice",
            map[string]any{
                "function": functionName,
            },
            nil,
        )
    }

    if false == token.IsIdentifier(request.PackageName) || "_" == request.PackageName {
        return "", nil, exception.NewError(
            "the generated package name is not a usable Go package name",
            map[string]any{
                "package": request.PackageName,
            },
            nil,
        )
    }

    /* the generated function shares its file with the fixed import aliases and the identifiers the provider bodies spell; a name claiming one of them cannot compile, so it fails here, at its cause */
    if true == importAliases.takenAlias[functionName] ||
        containerContractImportAlias == functionName ||
        containerImportAlias == functionName ||
        configImportAlias == functionName ||
        exceptionImportAlias == functionName ||
        mathImportAlias == functionName {
        return "", nil, exception.NewError(
            "the generated function name collides with an identifier the generated file spells",
            map[string]any{
                "function": functionName,
            },
            nil,
        )
    }

    if true == importAliases.takenAlias[scopedFunctionName] ||
        containerContractImportAlias == scopedFunctionName ||
        containerImportAlias == scopedFunctionName ||
        configImportAlias == scopedFunctionName ||
        exceptionImportAlias == scopedFunctionName ||
        mathImportAlias == scopedFunctionName {
        return "", nil, exception.NewError(
            "the generated scoped function name collides with an identifier the generated file spells",
            map[string]any{
                "function": scopedFunctionName,
            },
            nil,
        )
    }

    importAliases.reserveIdentifier(functionName)
    importAliases.reserveIdentifier(scopedFunctionName)
    importAliases.reserve(containerContractImportPath, containerContractImportAlias)
    importAliases.reserve(containerImportPath, containerImportAlias)
    importAliases.reserve(configImportPath, configImportAlias)
    importAliases.reserve(exceptionImportPath, exceptionImportAlias)
    importAliases.reserve(mathImportPath, mathImportAlias)

    providerBlocks := make([]string, 0)
    scopedProviderBlocks := make([]string, 0)
    unusedDirectiveBinds := make([]string, 0)

    /* two constructors that register under one container key panic at the first boot of the generated file, far from the generation that reported success; the collision is keyed here exactly as the emitted registration keys it — by the returned type for a type registration, by the named constant for a named one — so it fails at generation, naming both sites. A name constant's VALUE is not read from the source, so a type registration and a name registration that happen to spell the same service name, or two distinct constants holding one value, stay out of reach of this check. */
    registrationSites := make(map[string]*Constructor)

    for _, packageBinding := range request.BindSet.Packages() {
        /* both halves land in the generated file and in the walk: an empty import path renders an import of "", and an empty directory joins to the project root and silently scans the whole tree as one package */
        if "" == packageBinding.ImportPath() || "" == packageBinding.Directory() {
            return "", nil, exception.NewError(
                "a package binding must declare both an import path and a directory",
                map[string]any{
                    "importPath": packageBinding.ImportPath(),
                    "directory":  packageBinding.Directory(),
                },
                nil,
            )
        }

        scanResult, scanErr := Scan(request.ProjectDirectory, packageBinding, request.BuildTags)
        if nil != scanErr {
            return "", nil, scanErr
        }

        report.Skipped = append(report.Skipped, scanResult.Skipped...)
        report.SkippedVendorDirectories = append(report.SkippedVendorDirectories, scanResult.SkippedVendorDirectories...)
        report.ExcludedFiles = append(report.ExcludedFiles, scanResult.ExcludedFiles...)

        for _, pattern := range scanResult.UnusedExcludes {
            report.UnusedExcludes = append(report.UnusedExcludes, packageBinding.ImportPath()+"."+pattern)
        }

        for _, constructor := range scanResult.Constructors {
            registrationKey := registrationKeyFor(constructor)
            if existing, taken := registrationSites[registrationKey]; true == taken {
                return "", nil, exception.NewError(
                    "two constructors register the same service",
                    map[string]any{
                        "first":  existing.Name + " (" + existing.File + ":" + strconv.Itoa(existing.Line) + ")",
                        "second": constructor.Name + " (" + constructor.File + ":" + strconv.Itoa(constructor.Line) + ")",
                    },
                    nil,
                )
            }
            registrationSites[registrationKey] = constructor
            resolvedArguments, constructorUnusedDirectiveBinds, resolveErr := resolveArguments(
                constructor,
                packageBinding,
                request,
                usedBinds,
                report,
            )
            if nil != resolveErr {
                return "", nil, resolveErr
            }

            unusedDirectiveBinds = append(unusedDirectiveBinds, constructorUnusedDirectiveBinds...)

            if true == constructor.IsScoped {
                scopedProviderBlocks = append(
                    scopedProviderBlocks,
                    renderProvider(constructor, resolvedArguments, importAliases),
                )

                report.ScopedConstructorCount = report.ScopedConstructorCount + 1

                continue
            }

            providerBlocks = append(
                providerBlocks,
                renderProvider(constructor, resolvedArguments, importAliases),
            )

            report.ConstructorCount = report.ConstructorCount + 1
        }
    }

    report.UnusedBinds = collectUnusedBinds(request.BindSet, usedBinds, unusedDirectiveBinds)

    source := renderFile(
        request.PackageName,
        functionName,
        scopedFunctionName,
        importAliases,
        providerBlocks,
        scopedProviderBlocks,
    )

    return source, report, nil
}

/* registrationKeyFor derives the key the emitted registration will claim in the container, so two constructors claiming one key fail at generation instead of at boot. A type registration is keyed by the returned type — import path and bare type name, with the pointer stars kept, since the container derives different names for T and *T — and a named registration by the constant that names it. The two lifetimes register through different registrars and do not collide with each other: a scoped registration of a type is what deliberately shadows the container one inside a scope. */
func registrationKeyFor(constructor *Constructor) string {
    lifetime := "container"
    if true == constructor.IsScoped {
        lifetime = "scoped"
    }

    if "" != constructor.ServiceNameIdentifier {
        return lifetime + " name " + constructor.ImportPath + "." + constructor.ServiceNameIdentifier
    }

    typeName := constructor.ReturnType.Expression

    stars := ""
    for true == strings.HasPrefix(typeName, "*") {
        stars = stars + "*"
        typeName = strings.TrimPrefix(typeName, "*")
    }

    if separatorIndex := strings.Index(typeName, "."); 0 <= separatorIndex {
        typeName = typeName[separatorIndex+1:]
    }

    return lifetime + " type " + stars + constructor.ReturnType.ImportPath + "." + typeName
}

type resolvedArgument struct {
    argument      *Argument
    parameterName string
    variableName  string
}

func resolveArguments(
    constructor *Constructor,
    packageBinding *PackageBinding,
    request *GenerateRequest,
    usedBinds map[string]bool,
    report *GenerateReport,
) ([]*resolvedArgument, []string, error) {
    resolvedArguments := make([]*resolvedArgument, 0, len(constructor.Arguments))
    matchedDirectiveBinds := make(map[string]bool)

    for _, argument := range constructor.Arguments {
        resolved := &resolvedArgument{
            argument:     argument,
            variableName: argument.Name,
        }

        if false == argument.IsScalar {
            resolvedArguments = append(resolvedArguments, resolved)

            continue
        }

        parameterName, bindScope, found := lookupBind(constructor, packageBinding, request.BindSet, argument.Name)
        if false == found {
            return nil, nil, exception.NewError(
                "no bind covers a scalar constructor argument",
                map[string]any{
                    "constructor": constructor.Name,
                    "argument":    argument.Name,
                    "type":        argument.Type.Expression,
                    "file":        constructor.File,
                    "line":        constructor.Line,
                },
                nil,
            )
        }

        /* an empty declared-parameter set disables this check, and the field's contract is to say so rather than silently assume every target exists; the flag is raised only when a bind actually went unchecked, so a set with no scalar arguments reports nothing */
        if 0 == len(request.DeclaredParameters) {
            report.BindTargetsUnchecked = true
        }

        if 0 < len(request.DeclaredParameters) && false == request.DeclaredParameters[parameterName] {
            return nil, nil, exception.NewError(
                "a bind points at a parameter the application does not declare",
                map[string]any{
                    "constructor": constructor.Name,
                    "argument":    argument.Name,
                    "parameter":   parameterName,
                    "file":        constructor.File,
                    "line":        constructor.Line,
                },
                nil,
            )
        }

        if bindScopeDirective == bindScope {
            matchedDirectiveBinds[argument.Name] = true
        }

        if bindScopeGlobal == bindScope {
            usedBinds[globalBindKey(argument.Name)] = true

            report.GlobalBindReach[argument.Name] = append(
                report.GlobalBindReach[argument.Name],
                constructor.Name,
            )
        }

        if bindScopePackage == bindScope {
            usedBinds[packageBindKey(packageBinding.ImportPath(), argument.Name)] = true
        }

        resolved.parameterName = parameterName

        resolvedArguments = append(resolvedArguments, resolved)
    }

    /* a directive bind naming an argument the constructor does not have — or one that is a service rather than a scalar — otherwise vanishes without a trace, and it sits right next to the constructor it fails to affect */
    unusedDirectiveBinds := make([]string, 0)
    for bindName := range constructor.DirectiveBinds {
        if false == matchedDirectiveBinds[bindName] {
            unusedDirectiveBinds = append(unusedDirectiveBinds, constructor.Name+"."+bindName)
        }
    }

    return resolvedArguments, unusedDirectiveBinds, nil
}

type bindScopeKind int

const (
    bindScopeDirective bindScopeKind = iota
    bindScopePackage
    bindScopeGlobal
)

func lookupBind(
    constructor *Constructor,
    packageBinding *PackageBinding,
    bindSet *BindSet,
    argumentName string,
) (string, bindScopeKind, bool) {
    if parameterName, exists := constructor.DirectiveBinds[argumentName]; true == exists {
        return parameterName, bindScopeDirective, true
    }

    if parameterName, exists := packageBinding.Bind(argumentName); true == exists {
        return parameterName, bindScopePackage, true
    }

    if parameterName, exists := bindSet.GlobalBind(argumentName); true == exists {
        return parameterName, bindScopeGlobal, true
    }

    return "", bindScopeGlobal, false
}

func globalBindKey(argumentName string) string {
    return "global:" + argumentName
}

func packageBindKey(importPath string, argumentName string) string {
    return "package:" + importPath + ":" + argumentName
}

func collectUnusedBinds(bindSet *BindSet, usedBinds map[string]bool, unusedDirectiveBinds []string) []string {
    unused := make([]string, 0)

    unused = append(unused, unusedDirectiveBinds...)

    for _, argumentName := range bindSet.GlobalBindNames() {
        if false == usedBinds[globalBindKey(argumentName)] {
            unused = append(unused, argumentName)
        }
    }

    for _, packageBinding := range bindSet.Packages() {
        for _, argumentName := range packageBinding.BindNames() {
            if false == usedBinds[packageBindKey(packageBinding.ImportPath(), argumentName)] {
                unused = append(unused, packageBinding.ImportPath()+"."+argumentName)
            }
        }
    }

    sort.Strings(unused)

    return unused
}
