package wiring

import (
    "sort"

    "github.com/precision-soft/melody/v3/exception"
)

const (
    indent            = "    "
    generatedFileNote = "/* Code generated by melody:wiring:generate. DO NOT EDIT. */"

    configImportPath             = "github.com/precision-soft/melody/v3/config"
    containerImportPath          = "github.com/precision-soft/melody/v3/container"
    containerContractImportPath  = "github.com/precision-soft/melody/v3/container/contract"
    containerContractImportAlias = "containercontract"
    configImportAlias            = "melodyconfig"
    containerImportAlias         = "melodycontainer"
)

type GenerateRequest struct {
    ProjectDirectory string
    PackageName      string
    FunctionName     string
    BindSet          *BindSet
    /* DeclaredParameters is the set of parameter names the application declares. When it is empty the generator cannot check a bind target and says so instead of assuming the target exists. */
    DeclaredParameters map[string]bool
}

type GenerateReport struct {
    ConstructorCount int
    Skipped          []*SkippedConstructor
    UnusedBinds      []string
    GlobalBindReach  map[string][]string
}

/* Generate scans every declared package and renders the registration source. It fails on the first constructor whose scalar argument no bind covers: an unfilled scalar has no safe default, and letting it through would move the failure to a runtime far from its cause. */
func Generate(request *GenerateRequest) (string, *GenerateReport, error) {
    if nil == request || nil == request.BindSet {
        return "", nil, exception.NewError("a bind set is required to generate the wiring", nil, nil)
    }

    functionName := request.FunctionName
    if "" == functionName {
        functionName = "RegisterGeneratedServices"
    }

    report := &GenerateReport{
        Skipped:         make([]*SkippedConstructor, 0),
        UnusedBinds:     make([]string, 0),
        GlobalBindReach: make(map[string][]string),
    }

    usedBinds := make(map[string]bool)

    importAliases := newImportAliasTable()
    importAliases.reserve(containerContractImportPath, containerContractImportAlias)
    importAliases.reserve(containerImportPath, containerImportAlias)

    providerBlocks := make([]string, 0)
    requiresConfiguration := false

    for _, packageBinding := range request.BindSet.Packages() {
        scanResult, scanErr := Scan(request.ProjectDirectory, packageBinding)
        if nil != scanErr {
            return "", nil, scanErr
        }

        report.Skipped = append(report.Skipped, scanResult.Skipped...)

        for _, constructor := range scanResult.Constructors {
            resolvedArguments, resolveErr := resolveArguments(
                constructor,
                packageBinding,
                request,
                usedBinds,
                report,
            )
            if nil != resolveErr {
                return "", nil, resolveErr
            }

            for _, resolvedArgument := range resolvedArguments {
                if true == resolvedArgument.argument.IsScalar {
                    requiresConfiguration = true
                }
            }

            providerBlocks = append(
                providerBlocks,
                renderProvider(constructor, resolvedArguments, importAliases),
            )

            report.ConstructorCount = report.ConstructorCount + 1
        }
    }

    if true == requiresConfiguration {
        importAliases.reserve(configImportPath, configImportAlias)
    }

    report.UnusedBinds = collectUnusedBinds(request.BindSet, usedBinds)

    source := renderFile(
        request.PackageName,
        functionName,
        importAliases,
        providerBlocks,
        requiresConfiguration,
    )

    return source, report, nil
}

type resolvedArgument struct {
    argument      *Argument
    parameterName string
    variableName  string
}

func resolveArguments(
    constructor *Constructor,
    packageBinding *PackageBinding,
    request *GenerateRequest,
    usedBinds map[string]bool,
    report *GenerateReport,
) ([]*resolvedArgument, error) {
    resolvedArguments := make([]*resolvedArgument, 0, len(constructor.Arguments))

    for _, argument := range constructor.Arguments {
        resolved := &resolvedArgument{
            argument:     argument,
            variableName: argument.Name,
        }

        if false == argument.IsScalar {
            resolvedArguments = append(resolvedArguments, resolved)

            continue
        }

        parameterName, bindScope, found := lookupBind(constructor, packageBinding, request.BindSet, argument.Name)
        if false == found {
            return nil, exception.NewError(
                "no bind covers a scalar constructor argument",
                map[string]any{
                    "constructor": constructor.Name,
                    "argument":    argument.Name,
                    "type":        argument.Type.Expression,
                    "file":        constructor.File,
                    "line":        constructor.Line,
                },
                nil,
            )
        }

        if 0 < len(request.DeclaredParameters) && false == request.DeclaredParameters[parameterName] {
            return nil, exception.NewError(
                "a bind points at a parameter the application does not declare",
                map[string]any{
                    "constructor": constructor.Name,
                    "argument":    argument.Name,
                    "parameter":   parameterName,
                    "file":        constructor.File,
                    "line":        constructor.Line,
                },
                nil,
            )
        }

        if bindScopeGlobal == bindScope {
            usedBinds[globalBindKey(argument.Name)] = true

            report.GlobalBindReach[argument.Name] = append(
                report.GlobalBindReach[argument.Name],
                constructor.Name,
            )
        }

        if bindScopePackage == bindScope {
            usedBinds[packageBindKey(packageBinding.ImportPath(), argument.Name)] = true
        }

        resolved.parameterName = parameterName

        resolvedArguments = append(resolvedArguments, resolved)
    }

    return resolvedArguments, nil
}

type bindScopeKind int

const (
    bindScopeDirective bindScopeKind = iota
    bindScopePackage
    bindScopeGlobal
)

func lookupBind(
    constructor *Constructor,
    packageBinding *PackageBinding,
    bindSet *BindSet,
    argumentName string,
) (string, bindScopeKind, bool) {
    if parameterName, exists := constructor.DirectiveBinds[argumentName]; true == exists {
        return parameterName, bindScopeDirective, true
    }

    if parameterName, exists := packageBinding.Bind(argumentName); true == exists {
        return parameterName, bindScopePackage, true
    }

    if parameterName, exists := bindSet.GlobalBind(argumentName); true == exists {
        return parameterName, bindScopeGlobal, true
    }

    return "", bindScopeGlobal, false
}

func globalBindKey(argumentName string) string {
    return "global:" + argumentName
}

func packageBindKey(importPath string, argumentName string) string {
    return "package:" + importPath + ":" + argumentName
}

func collectUnusedBinds(bindSet *BindSet, usedBinds map[string]bool) []string {
    unused := make([]string, 0)

    for _, argumentName := range bindSet.GlobalBindNames() {
        if false == usedBinds[globalBindKey(argumentName)] {
            unused = append(unused, argumentName)
        }
    }

    for _, packageBinding := range bindSet.Packages() {
        for _, argumentName := range packageBinding.BindNames() {
            if false == usedBinds[packageBindKey(packageBinding.ImportPath(), argumentName)] {
                unused = append(unused, packageBinding.ImportPath()+"."+argumentName)
            }
        }
    }

    sort.Strings(unused)

    return unused
}
